import typing

class Dict(typing.Dict):
    def to_dict(self) -> typing.Dict: ...
    def copy(self) -> typing.Dict: ...
    def deepcopy(self) -> typing.Dict: ...
    def update(self, *args: typing.List, **kwargs: typing.Dict): ...
    def setdefault(self, key: typing.Any, default: typing.Optional[typing.Any]) -> typing.Optional[typing.Any]: ...

